-- Semilla completa de referencias Foodbox/Comida para Supabase.
-- Ejecutar despues de sql/menu_catalog_supabase.sql.

insert into public.menu_reference_items
  (legacy_id, category_id, item_group, name, quantity_type, quantity, divisor, unit, display_order, active)
values
  ('gris_1', 2, 'gris', 'Brocheta capresse', 'fijo', 1, null, 'ud', 1, true),
  ('gris_2', 2, 'gris', 'Rollito de primavera con salsa sweet chili', 'fijo', 2, null, 'uds', 2, true),
  ('gris_3', 2, 'gris', 'Croquetas de jamón', 'fijo', 2, null, 'uds', 3, true),
  ('gris_4', 2, 'gris', 'Croquetas de boletus', 'fijo', 2, null, 'uds', 4, true),
  ('gris_5', 2, 'gris', 'Empanadilla de atún', 'fijo', 2, null, 'uds', 5, true),
  ('gris_6', 2, 'gris', 'Tabla de embutidos ibéricos con pan airbag', 'porPax', 15, null, 'grs', 6, true),
  ('gris_7', 2, 'gris', 'Falafel con salsa de yogurt', 'fijo', 2, null, 'uds', 7, true),
  ('gris_8', 2, 'gris', 'Wraps de mortadela trufada', 'fijo', 1, null, 'ud', 8, true),
  ('gris_9', 2, 'gris', 'Dip de hummus con pan naam', 'cadaXpax', 1, 10, 'ud', 9, true),
  ('gris_10', 2, 'gris', 'Tartaleta de nuestra ensaladilla rusa', 'fijo', 2, null, 'uds', 10, true),
  ('gris_11', 2, 'gris', 'Pulguita de tortilla de patata', 'fijo', 1, null, 'ud', 11, true),
  ('gris_12', 2, 'gris', 'Pulguita de verduras asadas', 'fijo', 1, null, 'ud', 12, true),
  ('gris_13', 2, 'gris', 'Pulguita de pollo al curry', 'fijo', 1, null, 'ud', 13, true),
  ('gris_14', 2, 'gris', 'Pulguita de aguacate y tomate', 'fijo', 1, null, 'ud', 14, true),
  ('gris_15', 2, 'gris', 'Quesadilla sincronizada', 'fijo', 2, null, 'uds', 15, true),
  ('gris_16', 2, 'gris', 'Gyozas con salsa de soja', 'fijo', 2, null, 'uds', 16, true),
  ('gris_17', 2, 'gris', 'Mini croissant mixto', 'fijo', 1, null, 'ud', 17, true),
  ('gris_18', 2, 'gris', 'Mini croissant de nuestra ensaladilla rusa', 'fijo', 1, null, 'ud', 18, true),
  ('gris_19', 2, 'gris', 'Mini sándwich de bacon y mayomostaza', 'fijo', 2, null, 'uds', 19, true),
  ('gris_20', 2, 'gris', 'Mini sándwich de tortilla de patata', 'fijo', 2, null, 'uds', 20, true),
  ('gris_21', 2, 'gris', 'Mini sándwich de crema de aguacate y tomate', 'fijo', 2, null, 'uds', 21, true),
  ('gris_22', 2, 'gris', 'Mini sándwich de pollo al curry', 'fijo', 2, null, 'uds', 22, true),
  ('gris_23', 2, 'gris', 'Mini sándwich vegetal', 'fijo', 2, null, 'uds', 23, true),
  ('gris_24', 2, 'gris', 'Mini sándwich de pechuga de pavo y queso edam', 'fijo', 2, null, 'uds', 24, true),
  ('gris_25', 2, 'gris', 'Mini bagel de proteína vegetal', 'fijo', 1, null, 'ud', 25, true),
  ('gris_26', 2, 'gris', 'Mini bagel de mortadela trufada', 'fijo', 1, null, 'ud', 26, true),
  ('gris_27', 2, 'gris', 'Mini bagel de salmón con crema de queso o aguacate', 'fijo', 1, null, 'ud', 27, true),
  ('gris_28', 2, 'gris', 'Mini bagel de pastrami y pepinillo agridulce', 'fijo', 1, null, 'ud', 28, true),
  ('gris_29', 2, 'gris', 'Mini bagel de roastbeef y cebolla confitada', 'fijo', 1, null, 'ud', 29, true),
  ('gris_30', 2, 'gris', 'Mini poke bowl de pollo teriyaki', 'fijo', 1, null, 'ud', 30, true),
  ('gris_31', 2, 'gris', 'Mini ensalada toscana', 'fijo', 1, null, 'ud', 31, true),
  ('gris_32', 2, 'gris', 'Mini Tabulé de cus cús y garbanzos', 'fijo', 1, null, 'ud', 32, true),
  ('gris_33', 2, 'gris', 'Mini Ensalada griega', 'fijo', 1, null, 'ud', 33, true),
  ('gris_34', 2, 'gris', 'Mini quiche lorraine tradicional (puerro y bacon)', 'fijo', 2, null, 'uds', 34, true),
  ('gris_35', 2, 'gris', 'Mini quiche de tomate seco y verduras', 'fijo', 2, null, 'uds', 35, true),
  ('gris_36', 2, 'gris', 'Bao de pulled pork', 'fijo', 1, null, 'ud', 36, true),
  ('gris_37', 2, 'gris', 'Tortilla de patata', 'cadaXpax', 1, 10, 'ud', 37, true),
  ('gris_38', 2, 'gris', 'Tortilla de patata con padrón', 'cadaXpax', 1, 10, 'ud', 38, true),
  ('gris_39', 2, 'gris', 'Cheese rings con salsa BBQ', 'fijo', 2, null, 'uds', 39, true),
  ('rojo_101', 2, 'rojo', 'Totopos con guacamole', 'cadaXpax', 1, 10, 'ud', 1, true),
  ('rojo_102', 2, 'rojo', 'Empanadilla de calabaza y bacon', 'fijo', 2, null, 'uds', 2, true),
  ('rojo_103', 2, 'rojo', 'Empanadilla criolla', 'fijo', 2, null, 'uds', 3, true),
  ('rojo_104', 2, 'rojo', 'Empanadilla de espinaca y pasas', 'fijo', 2, null, 'uds', 4, true),
  ('rojo_105', 2, 'rojo', 'Croqueta de pollo', 'fijo', 2, null, 'uds', 5, true),
  ('rojo_106', 2, 'rojo', 'Mini sándwich de salmón y queso crema', 'fijo', 2, null, 'uds', 6, true),
  ('rojo_107', 2, 'rojo', 'Mini sándwich de paleta ibérica con tomate', 'fijo', 2, null, 'uds', 7, true),
  ('rojo_108', 2, 'rojo', 'Mini sándwich de mortadela, ricotta, tomate y pesto', 'fijo', 2, null, 'uds', 8, true),
  ('rojo_109', 2, 'rojo', 'Mini sándwich de pastrami', 'fijo', 2, null, 'uds', 9, true),
  ('rojo_110', 2, 'rojo', 'Mini sándwich de queso gorgonzola y nueces', 'fijo', 2, null, 'uds', 10, true),
  ('rojo_111', 2, 'rojo', 'Tabla de paleta ibérica con pan airbag', 'porPax', 15, null, 'grs', 11, true),
  ('rojo_112', 2, 'rojo', 'Tabla de quesos internacionales con grissini, dátil y nueces', 'porPax', 15, null, 'grs', 12, true),
  ('rojo_113', 2, 'rojo', 'Wraps de salmón con aguacate', 'fijo', 1, null, 'ud', 13, true),
  ('rojo_114', 2, 'rojo', 'Wraps de pastrami', 'fijo', 1, null, 'ud', 14, true),
  ('rojo_115', 2, 'rojo', 'Focaccia de mortadela y queso ricotta', 'fijo', 1, null, 'ud', 15, true),
  ('rojo_116', 2, 'rojo', 'Mini poke bowl de salmón', 'fijo', 1, null, 'ud', 16, true),
  ('rojo_117', 2, 'rojo', 'Mini ensalada cesar', 'fijo', 1, null, 'ud', 17, true),
  ('rojo_118', 2, 'rojo', 'Mini ensalada de pasta y pesto con bacon y mozarella', 'fijo', 1, null, 'ud', 18, true),
  ('rojo_119', 2, 'rojo', 'Mini Ensalada L.A.', 'fijo', 1, null, 'ud', 19, true),
  ('rojo_120', 2, 'rojo', 'Pollo estilo kentucky con BBQ', 'fijo', 2, null, 'uds', 20, true),
  ('rojo_121', 2, 'rojo', 'Mini croissant de salmón con crema de queso', 'fijo', 1, null, 'ud', 21, true),
  ('rojo_122', 2, 'rojo', 'Mini tartaleta de crema de salmón', 'fijo', 2, null, 'uds', 22, true),
  ('rojo_123', 2, 'rojo', 'Mini quiche de bacalao con cebolla caramelizada', 'fijo', 2, null, 'uds', 23, true),
  ('rojo_124', 2, 'rojo', 'Pulguita de proteína vegetal', 'fijo', 1, null, 'ud', 24, true),
  ('rojo_125', 2, 'rojo', 'Pulguita de lomo y pimientos', 'fijo', 1, null, 'ud', 25, true),
  ('rojo_126', 2, 'rojo', 'Pulguita de paleta ibérica con tomate', 'fijo', 1, null, 'ud', 26, true),
  ('rojo_127', 2, 'rojo', 'Pulguita de nuestra ensaladilla rusa', 'fijo', 1, null, 'ud', 27, true),
  ('rojo_128', 2, 'rojo', 'Mini burger DECUATRO', 'fijo', 1, null, 'ud', 28, true),
  ('rojo_129', 2, 'rojo', 'Taco al pastor', 'fijo', 2, null, 'uds', 29, true),
  ('rojo_130', 2, 'rojo', 'Taco de tinga de pollo', 'fijo', 2, null, 'uds', 30, true),
  ('rojo_131', 2, 'rojo', 'Tortilla de patata con chistorra', 'cadaXpax', 1, 10, 'ud', 31, true),
  ('rojo_132', 2, 'rojo', 'Tortilla rellena de morcilla y piquillo', 'cadaXpax', 1, 10, 'ud', 32, true),
  ('rojo_133', 2, 'rojo', 'Tortilla rellena de ensalada de langostinos', 'cadaXpax', 1, 10, 'ud', 33, true),
  ('rojo_134', 2, 'rojo', 'Tortilla rellena de sobrasada y brie', 'cadaXpax', 1, 10, 'ud', 34, true),
  ('postre_201', 2, 'postre', 'Brocheta de fruta', 'postre', 1, null, 'ud', 1, true),
  ('postre_202', 2, 'postre', 'Mini cheescake', 'postre', 1, null, 'ud', 2, true),
  ('postre_203', 2, 'postre', 'Mini brownie con crema inglesa', 'postre', 1, null, 'ud', 3, true),
  ('postre_204', 2, 'postre', 'Mini arroz con leche', 'postre', 1, null, 'ud', 4, true),
  ('postre_205', 2, 'postre', 'Mini natillas con galleta', 'postre', 1, null, 'ud', 5, true),
  ('postre_206', 2, 'postre', 'Mini oreo sweet', 'postre', 1, null, 'ud', 6, true),
  ('postre_207', 2, 'postre', 'Mini kitkat shot', 'postre', 1, null, 'ud', 7, true),
  ('postre_208', 2, 'postre', 'Mini tiramisú', 'postre', 1, null, 'ud', 8, true),
  ('postre_209', 2, 'postre', 'Postres variados', 'postre', 1, null, 'ud', 9, true)
on conflict (category_id, menu_legacy_id, item_group, name) do update set
  legacy_id = excluded.legacy_id,
  quantity_type = excluded.quantity_type,
  quantity = excluded.quantity,
  divisor = excluded.divisor,
  unit = excluded.unit,
  display_order = excluded.display_order,
  active = excluded.active,
  updated_at = now();
