alter table public.service_logistics_materials
  add column if not exists conversion_a_stock numeric not null default 1;

insert into public.service_logistics_materials
  (tipo, nombre, subcategoria, presentacion, unidad_comanda, unidad_inventario, contenido_por_unidad, conversion_a_stock, cantidad_base, cantidad_por_pax, redondeo_a, auto_calcular, stock_total, orden, activo)
values
  ('bebidas', 'Coca normal', 'Refrescos', 'Paquete 24 uds', 'ud', 'ud', 24, 1, 0, 0, 1, false, 0, 10, true),
  ('bebidas', 'Coca light', 'Refrescos', 'Paquete 24 uds', 'ud', 'ud', 24, 1, 0, 0, 1, false, 0, 20, true),
  ('bebidas', 'Coca zero', 'Refrescos', 'Paquete 24 uds', 'ud', 'ud', 24, 1, 0, 0, 1, false, 0, 30, true),
  ('bebidas', 'Fanta limon', 'Refrescos', 'Paquete 24 uds', 'ud', 'ud', 24, 1, 0, 0, 1, false, 0, 40, true),
  ('bebidas', 'Fanta naranja', 'Refrescos', 'Paquete 24 uds', 'ud', 'ud', 24, 1, 0, 0, 1, false, 0, 50, true),
  ('bebidas', 'Sprite', 'Refrescos', 'Paquete 24 uds', 'ud', 'ud', 24, 1, 0, 0, 1, false, 0, 60, true),
  ('bebidas', 'Nestea', 'Refrescos', 'Paquete 24 uds', 'ud', 'ud', 24, 1, 0, 0, 1, false, 0, 70, true),
  ('bebidas', 'Acuarius limon', 'Refrescos', 'Paquete 24 uds', 'ud', 'ud', 24, 1, 0, 0, 1, false, 0, 80, true),
  ('bebidas', 'Acuarius naranja', 'Refrescos', 'Paquete 24 uds', 'ud', 'ud', 24, 1, 0, 0, 1, false, 0, 90, true),
  ('bebidas', 'Paquete tonica', 'Refrescos', 'Paquete 24 uds', 'ud', 'ud', 24, 1, 0, 0, 1, false, 0, 100, true),
  ('bebidas', 'Agua pet 33 cl', 'Agua', 'Paquete 20 uds', 'ud', 'ud', 20, 1, 0, 0, 1, false, 0, 110, true),
  ('bebidas', 'Agua eco brick', 'Agua', 'Paquete 24 uds', 'ud', 'ud', 24, 1, 0, 0, 1, false, 0, 120, true),
  ('bebidas', 'Agua 1.5 lt', 'Agua', 'Paquete 6 uds', 'ud', 'ud', 6, 1, 0, 0, 1, false, 0, 130, true),
  ('bebidas', 'Agua con gas', 'Agua', 'Paquete 6 uds', 'ud', 'ud', 6, 1, 0, 0, 1, false, 0, 140, true),
  ('bebidas', 'Cervezas', 'Cervezas', 'Paquete 24 uds', 'ud', 'ud', 24, 1, 0, 0, 1, false, 0, 150, true),
  ('bebidas', 'Cerveza sin', 'Cervezas', 'Paquete 24 uds', 'ud', 'ud', 24, 1, 0, 0, 1, false, 0, 160, true),
  ('bebidas', 'Litronas', 'Cervezas', 'Paquete 6 uds', 'ud', 'ud', 6, 1, 0, 0, 1, false, 0, 170, true),
  ('bebidas', 'Vino blanco', 'Vinos', 'Caja 6 botellas', 'botella', 'botella', 6, 1, 0, 0, 1, false, 0, 180, true),
  ('bebidas', 'Vino tinto', 'Vinos', 'Caja 6 botellas', 'botella', 'botella', 6, 1, 0, 0, 1, false, 0, 190, true),
  ('bebidas', 'Cava', 'Vinos', 'Caja 6 botellas', 'botella', 'botella', 6, 1, 0, 0, 1, false, 0, 200, true),
  ('bebidas', 'Tinto de verano', 'Vinos', 'Paquete 6 uds', 'ud', 'ud', 6, 1, 0, 0, 1, false, 0, 210, true),
  ('bebidas', 'Ron', 'Licores', null, 'botella', 'botella', 1, 1, 0, 0, 1, false, 0, 220, true),
  ('bebidas', 'Whisky', 'Licores', null, 'botella', 'botella', 1, 1, 0, 0, 1, false, 0, 230, true),
  ('bebidas', 'Ginebra', 'Licores', null, 'botella', 'botella', 1, 1, 0, 0, 1, false, 0, 240, true),
  ('bebidas', 'Vodka', 'Licores', null, 'botella', 'botella', 1, 1, 0, 0, 1, false, 0, 250, true),
  ('bebidas', 'Aperol', 'Licores', null, 'botella', 'botella', 1, 1, 0, 0, 1, false, 0, 260, true),
  ('bebidas', 'Malibu', 'Licores', null, 'botella', 'botella', 1, 1, 0, 0, 1, false, 0, 270, true),
  ('bebidas', 'Martini blanco', 'Licores', null, 'botella', 'botella', 1, 1, 0, 0, 1, false, 0, 280, true),
  ('bebidas', 'Martini rojo', 'Licores', null, 'botella', 'botella', 1, 1, 0, 0, 1, false, 0, 290, true),

  ('menaje', 'Vaso alto', 'Cristaleria', 'Barca 25 uds', 'ud', 'ud', 25, 1, 0, 0, 1, false, 0, 300, true),
  ('menaje', 'Vaso corto', 'Cristaleria', 'Barca 25 uds', 'ud', 'ud', 25, 1, 0, 0, 1, false, 0, 310, true),
  ('menaje', 'Copas vino', 'Cristaleria', 'Barca 36 uds', 'ud', 'ud', 36, 1, 0, 0, 1, false, 0, 320, true),
  ('menaje', 'Copa cava', 'Cristaleria', 'Barca 49 uds', 'ud', 'ud', 49, 1, 0, 0, 1, false, 0, 330, true),
  ('menaje', 'Fuente de agua', 'Servicio', null, 'ud', 'ud', 1, 1, 0, 0, 1, false, 0, 340, true),
  ('menaje', 'Botellas cristal', 'Servicio', null, 'ud', 'ud', 1, 1, 0, 0, 1, false, 0, 350, true),
  ('menaje', 'Platos postre', 'Vajilla', null, 'ud', 'ud', 1, 1, 0, 0, 1, false, 0, 360, true),
  ('menaje', 'Kit loza cafe (taza/plato/cucharilla)', 'Cafe', null, 'ud', 'ud', 1, 1, 0, 0, 1, false, 0, 370, true),
  ('menaje', 'Kit desechable cafe (vaso/azucar)', 'Cafe', null, 'ud', 'ud', 1, 1, 0, 0, 1, false, 0, 380, true),
  ('menaje', 'Vasos plastico', 'Desechables', null, 'ud', 'ud', 1, 1, 0, 0, 1, false, 0, 390, true),
  ('menaje', 'Foodbox vacias', 'Contenedores', null, 'ud', 'ud', 1, 1, 0, 0, 1, false, 0, 400, true),
  ('menaje', 'Servilletas', 'Textil', null, 'ud', 'ud', 1, 1, 0, 0, 1, false, 0, 410, true),

  ('material', 'Mesa tablero', 'Mobiliario', null, 'ud', 'ud', 1, 1, 0, 0, 1, false, 0, 500, true),
  ('material', 'Manteles algodon', 'Textil', null, 'ud', 'ud', 1, 1, 0, 0, 1, false, 0, 510, true),
  ('material', 'Mesa velador', 'Mobiliario', null, 'ud', 'ud', 1, 1, 0, 0, 1, false, 0, 520, true),
  ('material', 'Cubre velador', 'Textil', null, 'ud', 'ud', 1, 1, 0, 0, 1, false, 0, 530, true),
  ('material', 'Hielo', 'Bebidas', null, 'ud', 'ud', 1, 1, 0, 0, 1, false, 0, 540, true),
  ('material', 'Cajon enfriador', 'Bebidas', null, 'ud', 'ud', 1, 1, 0, 0, 1, false, 0, 550, true),
  ('material', 'Champaneras', 'Bebidas', null, 'ud', 'ud', 1, 1, 0, 0, 1, false, 0, 560, true),
  ('material', 'Cubiteras', 'Bebidas', null, 'ud', 'ud', 1, 1, 0, 0, 1, false, 0, 570, true),
  ('material', 'Pinzas hielo', 'Bebidas', null, 'ud', 'ud', 1, 1, 0, 0, 1, false, 0, 580, true),
  ('material', 'Cuadros d4', 'Identificacion', null, 'ud', 'ud', 1, 1, 0, 0, 1, false, 0, 590, true),
  ('material', 'Servilleteros', 'Servicio', null, 'ud', 'ud', 1, 1, 0, 0, 1, false, 0, 600, true),
  ('material', 'Alzadores', 'Presentacion', null, 'ud', 'ud', 1, 1, 0, 0, 1, false, 0, 610, true),
  ('material', 'Basuriles', 'Limpieza', null, 'ud', 'ud', 1, 1, 0, 0, 1, false, 0, 620, true),
  ('material', 'Mandiles', 'Uniformes', null, 'ud', 'ud', 1, 1, 0, 0, 1, false, 0, 630, true),
  ('material', 'Corbatas', 'Uniformes', null, 'ud', 'ud', 1, 1, 0, 0, 1, false, 0, 640, true),
  ('material', 'Cubo basura', 'Limpieza', null, 'ud', 'ud', 1, 1, 0, 0, 1, false, 0, 650, true),
  ('material', 'Cubo desbarase', 'Limpieza', null, 'ud', 'ud', 1, 1, 0, 0, 1, false, 0, 660, true),
  ('material', 'Bolsas basura', 'Limpieza', null, 'ud', 'ud', 1, 1, 0, 0, 1, false, 0, 670, true),
  ('material', 'Rollo papel', 'Limpieza', null, 'ud', 'ud', 1, 1, 0, 0, 1, false, 0, 680, true),
  ('material', 'Caja guantes', 'Limpieza', null, 'ud', 'ud', 1, 1, 0, 0, 1, false, 0, 690, true)
on conflict (tipo, nombre) do update set
  subcategoria = excluded.subcategoria,
  presentacion = excluded.presentacion,
  unidad_comanda = excluded.unidad_comanda,
  unidad_inventario = excluded.unidad_inventario,
  contenido_por_unidad = excluded.contenido_por_unidad,
  conversion_a_stock = excluded.conversion_a_stock,
  cantidad_base = excluded.cantidad_base,
  cantidad_por_pax = excluded.cantidad_por_pax,
  redondeo_a = excluded.redondeo_a,
  auto_calcular = excluded.auto_calcular,
  orden = excluded.orden,
  activo = true,
  updated_at = now();
