-- Semilla de composicion de desayunos para Supabase.
-- Ejecutar despues de sql/menu_catalog_supabase.sql.

insert into public.menu_reference_items
  (legacy_id, category_id, menu_legacy_id, item_group, name, quantity_type, quantity, divisor, unit, quantity_per_pax, selector_termo, options, pulguitas, fixed_flavor, sandwiches_count, display_order, active)
values
  ('healthy_cafe', 1, 1, 'desayuno', 'Termo de café', 'termo', 1, null, 'termo', 0.05, true, null, null, null, null, 1, true),
  ('healthy_leche', 1, 1, 'desayuno', 'Termo de leche', 'termo', 1, null, 'termo', 0.05, true, null, null, null, null, 2, true),
  ('healthy_leche_sin_lactosa', 1, 1, 'desayuno', 'Termo leche sin lactosa', 'leche_especial', 1, null, 'termo', 0, true, null, null, null, null, 3, true),
  ('healthy_leche_veg', 1, 1, 'desayuno', 'Termo leche vegetal', 'leche_especial', 1, null, 'termo', 0, true, null, null, null, null, 4, true),
  ('healthy_infusion', 1, 1, 'desayuno', 'Termo de infusión', 'termo', 1, null, 'termo', 0.05, true, null, null, null, null, 5, true),
  ('healthy_tostada', 1, 1, 'desayuno', 'Tostada de aguacate y tomate', 'simple', 1, null, 'uds', 1, false, null, null, null, null, 6, true),
  ('healthy_zumo', 1, 1, 'desayuno', 'Zumo natural', 'zumo', 1, null, 'litro', 0.2, false, null, null, null, null, 7, true),
  ('healthy_bolleria', 1, 1, 'desayuno', 'Bollería', 'bolleria', 1, null, 'uds', 1, false, '["Mini bollería variada","Mini croissant","Mini cinnamon roll","Mini trenza de chocolate","Mini envoltini chocolate","Mini envoltini crema","Mini envoltini frambuesa","Mini dots rellenos","Mini berlinas"]'::jsonb, null, null, null, 8, true),
  ('healthy_sandwich', 1, 1, 'desayuno', 'Mini sándwich', 'sandwich_multiple', 1, null, 'uds', 1, false, '["Paleta ibérica con tomate","Tortilla de patata","Nuestra ensaladilla rusa","Vegetal","Pollo al curry","Pechuga de pavo y queso edam","Atún, aceituna negra, lechuga y mahonesa","Crema de aguacate y tomate"]'::jsonb, null, null, 2, 9, true),
  ('healthy_fruta', 1, 1, 'desayuno', 'Vaso de fruta natural preparada', 'simple', 1, null, 'uds', 1, false, null, null, null, null, 10, true),
  ('classic_cafe', 1, 2, 'desayuno', 'Termo de café', 'termo', 1, null, 'termo', 0.05, true, null, null, null, null, 1, true),
  ('classic_leche', 1, 2, 'desayuno', 'Termo de leche', 'termo', 1, null, 'termo', 0.05, true, null, null, null, null, 2, true),
  ('classic_leche_sin_lactosa', 1, 2, 'desayuno', 'Termo leche sin lactosa', 'leche_especial', 1, null, 'termo', 0, true, null, null, null, null, 3, true),
  ('classic_leche_veg', 1, 2, 'desayuno', 'Termo leche vegetal', 'leche_especial', 1, null, 'termo', 0, true, null, null, null, null, 4, true),
  ('classic_infusion', 1, 2, 'desayuno', 'Termo de infusión', 'termo', 1, null, 'termo', 0.05, true, null, null, null, null, 5, true),
  ('classic_fruta', 1, 2, 'desayuno', 'Vasito fruta preparada', 'simple', 1, null, 'uds', 1, false, null, null, null, null, 6, true),
  ('classic_bolleria', 1, 2, 'desayuno', 'Bollería', 'bolleria', 1, null, 'uds', 2, false, '["Mini bollería variada","Mini croissant","Mini cinnamon roll","Mini trenza de chocolate","Mini envoltini chocolate","Mini envoltini crema","Mini envoltini frambuesa","Mini dots rellenos","Mini berlinas"]'::jsonb, null, null, null, 7, true),
  ('classic_sandwich', 1, 2, 'desayuno', 'Sandwiches', 'sandwich_multiple', 1, null, 'uds', 2, false, '["Paleta ibérica con tomate","Tortilla de patata","Nuestra ensaladilla rusa","Vegetal","Pollo al curry","Pechuga de pavo y queso edam","Atún, aceituna negra, lechuga y mahonesa","Crema de aguacate y tomate"]'::jsonb, null, null, 2, 8, true),
  ('classic_zumo', 1, 2, 'desayuno', 'Zumo natural', 'zumo', 1, null, 'litro', 0.2, false, null, null, null, null, 9, true),
  ('premium_cafe', 1, 3, 'desayuno', 'Termo de café', 'termo', 1, null, 'termo', 0.05, true, null, null, null, null, 1, true),
  ('premium_leche', 1, 3, 'desayuno', 'Termo de leche', 'termo', 1, null, 'termo', 0.05, true, null, null, null, null, 2, true),
  ('premium_leche_sin_lactosa', 1, 3, 'desayuno', 'Termo leche sin lactosa', 'leche_especial', 1, null, 'termo', 0, true, null, null, null, null, 3, true),
  ('premium_leche_veg', 1, 3, 'desayuno', 'Termo leche vegetal', 'leche_especial', 1, null, 'termo', 0, true, null, null, null, null, 4, true),
  ('premium_infusion', 1, 3, 'desayuno', 'Termo de infusión', 'termo', 1, null, 'termo', 0.05, true, null, null, null, null, 5, true),
  ('premium_smoothie', 1, 3, 'desayuno', 'Smoothie "true fruit"', 'simple', 1, null, 'uds', 1, false, null, null, null, null, 6, true),
  ('premium_cookie', 1, 3, 'desayuno', 'Cookie o Muffin', 'sandwich', 1, null, 'uds', 1, false, '["Cookie","Muffin"]'::jsonb, null, null, null, 7, true),
  ('premium_fruta', 1, 3, 'desayuno', 'Fruta o Yogur', 'sandwich', 1, null, 'uds', 1, false, '["Vaso de fruta natural preparada","Yogur con granola y miel"]'::jsonb, null, null, null, 8, true),
  ('premium_bolleria', 1, 3, 'desayuno', 'Bollería', 'bolleria', 1, null, 'uds', 2, false, '["Mini bollería variada","Mini croissant","Mini cinnamon roll","Mini trenza de chocolate","Mini envoltini chocolate","Mini envoltini crema","Mini envoltini frambuesa","Mini dots rellenos","Mini berlinas"]'::jsonb, null, null, null, 9, true),
  ('premium_sandwich_o_pulguita', 1, 3, 'desayuno', '2 Sándwiches ó 1 Pulguita', 'sandwich_o_pulguita', 1, null, 'uds', 2, false, '["Paleta ibérica con tomate","Tortilla de patata","Nuestra ensaladilla rusa","Vegetal","Pollo al curry","Pechuga de pavo y queso edam","Atún, aceituna negra, lechuga y mahonesa","Crema de aguacate y tomate"]'::jsonb, '["Paleta ibérica con tomate","Tortilla española","Ensaladilla rusa","Vegetal","Pollo al curry"]'::jsonb, null, null, 10, true),
  ('veggie_cafe', 1, 4, 'desayuno', 'Termo de café', 'termo', 1, null, 'termo', 0.05, true, null, null, null, null, 1, true),
  ('veggie_leche', 1, 4, 'desayuno', 'Termo de leche', 'termo', 1, null, 'termo', 0.05, true, null, null, null, null, 2, true),
  ('veggie_leche_sin_lactosa', 1, 4, 'desayuno', 'Termo leche sin lactosa', 'leche_especial', 1, null, 'termo', 0, true, null, null, null, null, 3, true),
  ('veggie_leche_veg', 1, 4, 'desayuno', 'Termo bebida vegetal', 'leche_especial', 1, null, 'termo', 0.05, true, null, null, null, null, 4, true),
  ('veggie_infusion', 1, 4, 'desayuno', 'Termo de infusión', 'termo', 1, null, 'termo', 0.05, true, null, null, null, null, 5, true),
  ('veggie_cookie', 1, 4, 'desayuno', 'Cookie vegana', 'simple', 1, null, 'uds', 1, false, null, null, null, null, 6, true),
  ('veggie_fruta', 1, 4, 'desayuno', 'Vaso de fruta natural preparada', 'simple', 1, null, 'uds', 1, false, null, null, null, null, 7, true),
  ('veggie_zumo', 1, 4, 'desayuno', 'Zumo de naranja natural', 'zumo', 1, null, 'litro', 0.2, false, null, null, null, null, 8, true),
  ('veggie_sandwich_vegetal', 1, 4, 'desayuno', 'Mini sándwich vegetal', 'sandwich_fijo', 1, null, 'uds', 1, false, null, null, 'Vegetal', null, 9, true),
  ('veggie_sandwich_aguacate', 1, 4, 'desayuno', 'Mini sándwich aguacate-tomate', 'sandwich_fijo', 1, null, 'uds', 1, false, null, null, 'Crema de aguacate con tomate', null, 10, true),
  ('welcome_cafe', 1, 17, 'desayuno', 'Termo de café', 'termo', 1, null, 'termo', 0.05, true, null, null, null, null, 1, true),
  ('welcome_leche', 1, 17, 'desayuno', 'Termo de leche', 'termo', 1, null, 'termo', 0.05, true, null, null, null, null, 2, true),
  ('welcome_leche_sin_lactosa', 1, 17, 'desayuno', 'Termo leche sin lactosa', 'leche_especial', 1, null, 'termo', 0, true, null, null, null, null, 3, true),
  ('welcome_leche_veg', 1, 17, 'desayuno', 'Termo leche vegetal', 'leche_especial', 1, null, 'termo', 0, true, null, null, null, null, 4, true),
  ('welcome_cookies', 1, 17, 'desayuno', 'Cookies o Pastas de té', 'sandwich', 1, null, 'uds', 2, false, '["Mini cookies","Pastas de té"]'::jsonb, null, null, null, 5, true),
  ('welcome_bolleria', 1, 17, 'desayuno', 'Mini bollería', 'bolleria', 1, null, 'uds', 1, false, '["Mini bollería variada","Mini croissant","Mini cinnamon roll","Mini trenza de chocolate","Mini envoltini chocolate","Mini envoltini crema","Mini envoltini frambuesa","Mini dots rellenos","Mini berlinas"]'::jsonb, null, null, null, 6, true)
on conflict (category_id, menu_legacy_id, item_group, name) do update set
  legacy_id = excluded.legacy_id,
  quantity_type = excluded.quantity_type,
  quantity = excluded.quantity,
  divisor = excluded.divisor,
  unit = excluded.unit,
  quantity_per_pax = excluded.quantity_per_pax,
  selector_termo = excluded.selector_termo,
  options = excluded.options,
  pulguitas = excluded.pulguitas,
  fixed_flavor = excluded.fixed_flavor,
  sandwiches_count = excluded.sandwiches_count,
  display_order = excluded.display_order,
  active = excluded.active,
  updated_at = now();
