create table if not exists public.service_menu_items (
  id uuid not null default gen_random_uuid(),
  service_category text not null,
  name text not null,
  quantity_type text not null default 'fijo',
  quantity numeric not null default 1,
  divisor integer null,
  unit text not null default 'ud',
  display_order integer not null default 0,
  active boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint service_menu_items_pkey primary key (id),
  constraint service_menu_items_category_name_key unique (service_category, name),
  constraint service_menu_items_quantity_type_check check (quantity_type in ('fijo', 'porPax', 'cadaXpax', 'postre'))
);

alter table public.service_menu_items enable row level security;

drop policy if exists "service_menu_items_read_authenticated" on public.service_menu_items;
create policy "service_menu_items_read_authenticated"
on public.service_menu_items
for select
to authenticated
using (active = true);

insert into public.service_menu_items
  (service_category, name, quantity_type, quantity, divisor, unit, display_order, active)
values
  ('vino', 'Patatas fritas', 'fijo', 1, null, 'ud', 1, true),
  ('vino', 'Encurtidos variados', 'fijo', 1, null, 'ud', 2, true),
  ('vino', 'Dados de queso', 'fijo', 1, null, 'ud', 3, true),
  ('vino', 'Tortilla de patata', 'fijo', 1, null, 'ud', 4, true),
  ('vino', 'Tabla de paleta ibérica con picos y pan airbag', 'fijo', 1, null, 'ud', 5, true),
  ('vino', 'Croquetas de jamón', 'fijo', 1, null, 'ud', 6, true),
  ('vino', 'Mini bagel de mortadela', 'fijo', 1, null, 'ud', 7, true),
  ('vino', 'Gilda', 'fijo', 1, null, 'ud', 8, true),
  ('vino', 'Tabla de quesos internacionales con grissini, dátiles y nueces', 'fijo', 1, null, 'ud', 9, true),
  ('vino', 'Pulguita de paleta ibérica con tomate', 'fijo', 1, null, 'ud', 10, true),
  ('vino', 'Croquetas de pollo', 'fijo', 1, null, 'ud', 11, true),
  ('vino', 'Empanadilla', 'fijo', 1, null, 'ud', 12, true),
  ('vino', 'Mini wraps de pastrami', 'fijo', 1, null, 'ud', 13, true),
  ('vino', 'Tortilla de patata con padrón', 'fijo', 1, null, 'ud', 14, true),
  ('vino', 'Brocheta capresse', 'fijo', 1, null, 'ud', 15, true),
  ('vino', 'Rollito de primavera con salsa sweet chili', 'fijo', 1, null, 'ud', 16, true),
  ('vino', 'Croquetas de boletus', 'fijo', 1, null, 'ud', 17, true),
  ('vino', 'Empanadilla de atún', 'fijo', 1, null, 'ud', 18, true),
  ('vino', 'Tabla de embutidos ibéricos con pan airbag', 'fijo', 1, null, 'ud', 19, true),
  ('vino', 'Falafel con salsa de yogurt', 'fijo', 1, null, 'ud', 20, true),
  ('vino', 'Wraps de mortadela trufada', 'fijo', 1, null, 'ud', 21, true),
  ('vino', 'Dip de hummus con pan naam', 'fijo', 1, null, 'ud', 22, true),
  ('vino', 'Tartaleta de nuestra ensaladilla rusa', 'fijo', 1, null, 'ud', 23, true),
  ('vino', 'Pulguita de tortilla de patata', 'fijo', 1, null, 'ud', 24, true),
  ('vino', 'Pulguita de verduras asadas', 'fijo', 1, null, 'ud', 25, true),
  ('vino', 'Quesadilla sincronizada', 'fijo', 1, null, 'ud', 26, true),
  ('vino', 'Gyozas con salsa de soja', 'fijo', 1, null, 'ud', 27, true),
  ('vino', 'Mini croissant mixto', 'fijo', 1, null, 'ud', 28, true),
  ('vino', 'Mini croissant de nuestra ensaladilla rusa', 'fijo', 1, null, 'ud', 29, true),
  ('vino', 'Mini sándwich de bacon y mayomostaza', 'fijo', 1, null, 'ud', 30, true),
  ('vino', 'Mini sándwich de tortilla de patata', 'fijo', 1, null, 'ud', 31, true),
  ('vino', 'Mini sándwich de crema de aguacate y tomate', 'fijo', 1, null, 'ud', 32, true),
  ('vino', 'Mini sándwich de pollo al curry', 'fijo', 1, null, 'ud', 33, true),
  ('vino', 'Mini sándwich vegetal', 'fijo', 1, null, 'ud', 34, true),
  ('vino', 'Mini sándwich de pechuga de pavo y queso edam', 'fijo', 1, null, 'ud', 35, true),
  ('vino', 'Mini bagel de roastbeef y cebolla confitada', 'fijo', 1, null, 'ud', 36, true),
  ('vino', 'Mini poke bowl de pollo teriyaki', 'fijo', 1, null, 'ud', 37, true),
  ('vino', 'Mini ensalada toscana', 'fijo', 1, null, 'ud', 38, true),
  ('vino', 'Mini Tabulé de cus cús y garbanzos', 'fijo', 1, null, 'ud', 39, true),
  ('vino', 'Mini Ensalada griega', 'fijo', 1, null, 'ud', 40, true),
  ('vino', 'Mini quiche lorraine tradicional (puerro y bacon)', 'fijo', 1, null, 'ud', 41, true),
  ('vino', 'Mini quiche de tomate seco y verduras', 'fijo', 1, null, 'ud', 42, true),
  ('vino', 'Bao de pulled pork', 'fijo', 1, null, 'ud', 43, true),
  ('vino', 'Cheese rings con salsa BBQ', 'fijo', 1, null, 'ud', 44, true),
  ('cocteles', 'Brocheta capresse', 'fijo', 1, null, 'ud', 1, true),
  ('cocteles', 'Rollito de primavera con salsa sweet chili', 'fijo', 2, null, 'uds', 2, true),
  ('cocteles', 'Croquetas de jamón', 'fijo', 2, null, 'uds', 3, true),
  ('cocteles', 'Croquetas de boletus', 'fijo', 2, null, 'uds', 4, true),
  ('cocteles', 'Empanadilla de atún', 'fijo', 2, null, 'uds', 5, true),
  ('cocteles', 'Tabla de embutidos ibéricos con pan airbag', 'porPax', 15, null, 'grs', 6, true),
  ('cocteles', 'Falafel con salsa de yogurt', 'fijo', 2, null, 'uds', 7, true),
  ('cocteles', 'Wraps de mortadela trufada', 'fijo', 1, null, 'ud', 8, true),
  ('cocteles', 'Dip de hummus con pan naam', 'cadaXpax', 1, 10, 'ud', 9, true),
  ('cocteles', 'Tartaleta de nuestra ensaladilla rusa', 'fijo', 2, null, 'uds', 10, true),
  ('cocteles', 'Pulguita de tortilla de patata', 'fijo', 1, null, 'ud', 11, true),
  ('cocteles', 'Pulguita de verduras asadas', 'fijo', 1, null, 'ud', 12, true),
  ('cocteles', 'Pulguita de pollo al curry', 'fijo', 1, null, 'ud', 13, true),
  ('cocteles', 'Pulguita de aguacate y tomate', 'fijo', 1, null, 'ud', 14, true),
  ('cocteles', 'Quesadilla sincronizada', 'fijo', 2, null, 'uds', 15, true),
  ('cocteles', 'Gyozas con salsa de soja', 'fijo', 2, null, 'uds', 16, true),
  ('cocteles', 'Mini croissant mixto', 'fijo', 1, null, 'ud', 17, true),
  ('cocteles', 'Mini croissant de nuestra ensaladilla rusa', 'fijo', 1, null, 'ud', 18, true),
  ('cocteles', 'Mini sándwich de bacon y mayomostaza', 'fijo', 2, null, 'uds', 19, true),
  ('cocteles', 'Mini sándwich de tortilla de patata', 'fijo', 2, null, 'uds', 20, true),
  ('cocteles', 'Mini sándwich de crema de aguacate y tomate', 'fijo', 2, null, 'uds', 21, true),
  ('cocteles', 'Mini sándwich de pollo al curry', 'fijo', 2, null, 'uds', 22, true),
  ('cocteles', 'Mini sándwich vegetal', 'fijo', 2, null, 'uds', 23, true),
  ('cocteles', 'Mini sándwich de pechuga de pavo y queso edam', 'fijo', 2, null, 'uds', 24, true),
  ('cocteles', 'Mini bagel de proteína vegetal', 'fijo', 1, null, 'ud', 25, true),
  ('cocteles', 'Mini bagel de mortadela trufada', 'fijo', 1, null, 'ud', 26, true),
  ('cocteles', 'Mini bagel de salmón con crema de queso o aguacate', 'fijo', 1, null, 'ud', 27, true),
  ('cocteles', 'Mini bagel de pastrami y pepinillo agridulce', 'fijo', 1, null, 'ud', 28, true),
  ('cocteles', 'Mini bagel de roastbeef y cebolla confitada', 'fijo', 1, null, 'ud', 29, true),
  ('cocteles', 'Mini poke bowl de pollo teriyaki', 'fijo', 1, null, 'ud', 30, true),
  ('cocteles', 'Mini ensalada toscana', 'fijo', 1, null, 'ud', 31, true),
  ('cocteles', 'Mini Tabulé de cus cús y garbanzos', 'fijo', 1, null, 'ud', 32, true),
  ('cocteles', 'Mini Ensalada griega', 'fijo', 1, null, 'ud', 33, true),
  ('cocteles', 'Mini quiche lorraine tradicional (puerro y bacon)', 'fijo', 2, null, 'uds', 34, true),
  ('cocteles', 'Mini quiche de tomate seco y verduras', 'fijo', 2, null, 'uds', 35, true),
  ('cocteles', 'Bao de pulled pork', 'fijo', 1, null, 'ud', 36, true),
  ('cocteles', 'Tortilla de patata', 'cadaXpax', 1, 10, 'ud', 37, true),
  ('cocteles', 'Tortilla de patata con padrón', 'cadaXpax', 1, 10, 'ud', 38, true),
  ('cocteles', 'Cheese rings con salsa BBQ', 'fijo', 2, null, 'uds', 39, true)
on conflict (service_category, name) do update set
  quantity_type = excluded.quantity_type,
  quantity = excluded.quantity,
  divisor = excluded.divisor,
  unit = excluded.unit,
  display_order = excluded.display_order,
  active = excluded.active,
  updated_at = now();
